package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/t1tc01/test-directive/common/jwt"
	"github.com/t1tc01/test-directive/graph"
	"github.com/t1tc01/test-directive/internal/users"
	"github.com/t1tc01/test-directive/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input *model.CreateUserInput) (string, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input *model.LoginInput) (string, error) {
	username := input.Username
	password := input.Password
	role := model.RoleUser

	correct := users.AuthenticateLogin(ctx, username, password)
	if !correct {
		return "", &users.WrongUsernameOrPasswordError{}
	}

	if username == "admin" {
		role = model.RoleAdmin
	}

	token, err := jwt.GenerateToken(username, role)
	if err != nil {
		return "", err
	}

	fmt.Println("PASS: Logged in, create token: \n", token)

	return token, nil

}

// Logout is the resolver for the logout field.
func (r *queryResolver) Logout(ctx context.Context) (string, error) {
	return "not implemented: Logout - logout", nil
}

// QuerryForAdmin is the resolver for the querryForAdmin field.
func (r *queryResolver) QuerryForAdmin(ctx context.Context) (string, error) {
	return "not implemented: QuerryForAdmin - querryForAdmin", nil
}

// QuerryForAll is the resolver for the querryForAll field.
func (r *queryResolver) QuerryForAll(ctx context.Context) (string, error) {
	return "not implemented: QuerryForAll - querryForAll", nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
